// Code generated by protoc-gen-go. DO NOT EDIT.
// source: audio.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamData struct {
	SamplesLeft          []float64            `protobuf:"fixed64,1,rep,packed,name=samplesLeft,proto3" json:"samplesLeft,omitempty"`
	SamplesRight         []float64            `protobuf:"fixed64,2,rep,packed,name=samplesRight,proto3" json:"samplesRight,omitempty"`
	NextAt               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=nextAt,proto3" json:"nextAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StreamData) Reset()         { *m = StreamData{} }
func (m *StreamData) String() string { return proto.CompactTextString(m) }
func (*StreamData) ProtoMessage()    {}
func (*StreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fae679ade197b92f, []int{0}
}

func (m *StreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamData.Unmarshal(m, b)
}
func (m *StreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamData.Marshal(b, m, deterministic)
}
func (m *StreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamData.Merge(m, src)
}
func (m *StreamData) XXX_Size() int {
	return xxx_messageInfo_StreamData.Size(m)
}
func (m *StreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamData proto.InternalMessageInfo

func (m *StreamData) GetSamplesLeft() []float64 {
	if m != nil {
		return m.SamplesLeft
	}
	return nil
}

func (m *StreamData) GetSamplesRight() []float64 {
	if m != nil {
		return m.SamplesRight
	}
	return nil
}

func (m *StreamData) GetNextAt() *timestamp.Timestamp {
	if m != nil {
		return m.NextAt
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamData)(nil), "message.StreamData")
}

func init() { proto.RegisterFile("audio.proto", fileDescriptor_fae679ade197b92f) }

var fileDescriptor_fae679ade197b92f = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0x4d, 0xc9,
	0xcc, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x27, 0x95, 0xa6, 0xe9, 0x97,
	0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x54, 0x2a, 0xb5, 0x31, 0x72, 0x71, 0x05,
	0x97, 0x14, 0xa5, 0x26, 0xe6, 0xba, 0x24, 0x96, 0x24, 0x0a, 0x29, 0x70, 0x71, 0x17, 0x27, 0xe6,
	0x16, 0xe4, 0xa4, 0x16, 0xfb, 0xa4, 0xa6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x06, 0x21,
	0x0b, 0x09, 0x29, 0x71, 0xf1, 0x40, 0xb9, 0x41, 0x99, 0xe9, 0x19, 0x25, 0x12, 0x4c, 0x60, 0x25,
	0x28, 0x62, 0x42, 0x46, 0x5c, 0x6c, 0x79, 0xa9, 0x15, 0x25, 0x8e, 0x25, 0x12, 0xcc, 0x0a, 0x8c,
	0x1a, 0xdc, 0x46, 0x52, 0x7a, 0x10, 0x67, 0xe8, 0xc1, 0x9c, 0xa1, 0x17, 0x02, 0x73, 0x46, 0x10,
	0x54, 0x65, 0x12, 0x1b, 0x58, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xb9, 0x2c, 0xae,
	0xc8, 0x00, 0x00, 0x00,
}
