// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/discovery.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Announce struct {
	ServiceNumber        uint32   `protobuf:"varint,1,opt,name=service_number,json=serviceNumber,proto3" json:"service_number,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Announce) Reset()         { *m = Announce{} }
func (m *Announce) String() string { return proto.CompactTextString(m) }
func (*Announce) ProtoMessage()    {}
func (*Announce) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c88b175b62d0e4c, []int{0}
}

func (m *Announce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Announce.Unmarshal(m, b)
}
func (m *Announce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Announce.Marshal(b, m, deterministic)
}
func (m *Announce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Announce.Merge(m, src)
}
func (m *Announce) XXX_Size() int {
	return xxx_messageInfo_Announce.Size(m)
}
func (m *Announce) XXX_DiscardUnknown() {
	xxx_messageInfo_Announce.DiscardUnknown(m)
}

var xxx_messageInfo_Announce proto.InternalMessageInfo

func (m *Announce) GetServiceNumber() uint32 {
	if m != nil {
		return m.ServiceNumber
	}
	return 0
}

func (m *Announce) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func init() {
	proto.RegisterType((*Announce)(nil), "message.Announce")
}

func init() {
	proto.RegisterFile("message/discovery.proto", fileDescriptor_9c88b175b62d0e4c)
}

var fileDescriptor_9c88b175b62d0e4c = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x4f, 0xc9, 0x2c, 0x4e, 0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x4a, 0x28, 0x05, 0x71, 0x71, 0x38, 0xe6, 0xe5, 0xe5, 0x97,
	0xe6, 0x25, 0xa7, 0x0a, 0xa9, 0x72, 0xf1, 0x15, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xc6, 0xe7,
	0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xf1, 0x42, 0x45, 0xfd,
	0xc0, 0x82, 0x42, 0xf2, 0x5c, 0xdc, 0x29, 0xa9, 0x10, 0x55, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x5c, 0x10, 0x21, 0xbf, 0xc4, 0xdc, 0xd4, 0x24, 0x36, 0xb0, 0x1d, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xb8, 0x1c, 0xdb, 0x7e, 0x00, 0x00, 0x00,
}
