// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/internal.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PeerOnline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerOnline) Reset()         { *m = PeerOnline{} }
func (m *PeerOnline) String() string { return proto.CompactTextString(m) }
func (*PeerOnline) ProtoMessage()    {}
func (*PeerOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fdf317f37f1c40, []int{0}
}

func (m *PeerOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerOnline.Unmarshal(m, b)
}
func (m *PeerOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerOnline.Marshal(b, m, deterministic)
}
func (m *PeerOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerOnline.Merge(m, src)
}
func (m *PeerOnline) XXX_Size() int {
	return xxx_messageInfo_PeerOnline.Size(m)
}
func (m *PeerOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerOnline.DiscardUnknown(m)
}

var xxx_messageInfo_PeerOnline proto.InternalMessageInfo

func (m *PeerOnline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PeerOffline struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerOffline) Reset()         { *m = PeerOffline{} }
func (m *PeerOffline) String() string { return proto.CompactTextString(m) }
func (*PeerOffline) ProtoMessage()    {}
func (*PeerOffline) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fdf317f37f1c40, []int{1}
}

func (m *PeerOffline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerOffline.Unmarshal(m, b)
}
func (m *PeerOffline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerOffline.Marshal(b, m, deterministic)
}
func (m *PeerOffline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerOffline.Merge(m, src)
}
func (m *PeerOffline) XXX_Size() int {
	return xxx_messageInfo_PeerOffline.Size(m)
}
func (m *PeerOffline) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerOffline.DiscardUnknown(m)
}

var xxx_messageInfo_PeerOffline proto.InternalMessageInfo

func (m *PeerOffline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type WriteRequest struct {
	DeviceName           string   `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65fdf317f37f1c40, []int{2}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *WriteRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerOnline)(nil), "message.PeerOnline")
	proto.RegisterType((*PeerOffline)(nil), "message.PeerOffline")
	proto.RegisterType((*WriteRequest)(nil), "message.WriteRequest")
}

func init() {
	proto.RegisterFile("message/internal.proto", fileDescriptor_65fdf317f37f1c40)
}

var fileDescriptor_65fdf317f37f1c40 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a, 0x2b, 0xc9, 0x70, 0x71, 0x05, 0xa4, 0xa6, 0x16, 0xf9, 0xe7,
	0xe5, 0x64, 0xe6, 0xa5, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x31, 0x65, 0xa6, 0x28, 0xc9, 0x72, 0x71, 0x83, 0x65, 0xd3, 0xd2, 0xb0, 0x4a, 0x7b, 0x72,
	0xf1, 0x84, 0x17, 0x65, 0x96, 0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x73,
	0x71, 0xa7, 0xa4, 0x96, 0x65, 0x26, 0xa7, 0xc6, 0xe7, 0x25, 0xe6, 0xa6, 0x42, 0x15, 0x72, 0x41,
	0x84, 0xfc, 0x12, 0x73, 0x53, 0x85, 0x24, 0xb8, 0x60, 0x16, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xf0,
	0x04, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0x77, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x26, 0xf7,
	0xe7, 0x4e, 0xb1, 0x00, 0x00, 0x00,
}
