// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceAllowed struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceAllowed) Reset()         { *m = DeviceAllowed{} }
func (m *DeviceAllowed) String() string { return proto.CompactTextString(m) }
func (*DeviceAllowed) ProtoMessage()    {}
func (*DeviceAllowed) Descriptor() ([]byte, []int) {
	return fileDescriptor_b29fb4a916ab9601, []int{0}
}

func (m *DeviceAllowed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceAllowed.Unmarshal(m, b)
}
func (m *DeviceAllowed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceAllowed.Marshal(b, m, deterministic)
}
func (m *DeviceAllowed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceAllowed.Merge(m, src)
}
func (m *DeviceAllowed) XXX_Size() int {
	return xxx_messageInfo_DeviceAllowed.Size(m)
}
func (m *DeviceAllowed) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceAllowed.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceAllowed proto.InternalMessageInfo

func (m *DeviceAllowed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeviceDisallowed struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDisallowed) Reset()         { *m = DeviceDisallowed{} }
func (m *DeviceDisallowed) String() string { return proto.CompactTextString(m) }
func (*DeviceDisallowed) ProtoMessage()    {}
func (*DeviceDisallowed) Descriptor() ([]byte, []int) {
	return fileDescriptor_b29fb4a916ab9601, []int{1}
}

func (m *DeviceDisallowed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDisallowed.Unmarshal(m, b)
}
func (m *DeviceDisallowed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDisallowed.Marshal(b, m, deterministic)
}
func (m *DeviceDisallowed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDisallowed.Merge(m, src)
}
func (m *DeviceDisallowed) XXX_Size() int {
	return xxx_messageInfo_DeviceDisallowed.Size(m)
}
func (m *DeviceDisallowed) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDisallowed.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDisallowed proto.InternalMessageInfo

func (m *DeviceDisallowed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceAllowed)(nil), "message.DeviceAllowed")
	proto.RegisterType((*DeviceDisallowed)(nil), "message.DeviceDisallowed")
}

func init() { proto.RegisterFile("mesh.proto", fileDescriptor_b29fb4a916ab9601) }

var fileDescriptor_b29fb4a916ab9601 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x4d, 0x2d, 0xce,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55,
	0x92, 0xe7, 0xe2, 0x75, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x75, 0xcc, 0xc9, 0xc9, 0x2f, 0x4f, 0x4d,
	0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c,
	0x51, 0x52, 0xe2, 0x12, 0x80, 0x28, 0x70, 0xc9, 0x2c, 0x4e, 0xc4, 0xae, 0x26, 0x89, 0x0d, 0x6c,
	0xa8, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x81, 0xbd, 0xc2, 0xa8, 0x62, 0x00, 0x00, 0x00,
}
