// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/ws.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WSDeviceStatus_Status int32

const (
	WSDeviceStatus_UNKNOWN     WSDeviceStatus_Status = 0
	WSDeviceStatus_NEW         WSDeviceStatus_Status = 1
	WSDeviceStatus_ONLINE      WSDeviceStatus_Status = 2
	WSDeviceStatus_OFFLINE     WSDeviceStatus_Status = 3
	WSDeviceStatus_DISAPPEARED WSDeviceStatus_Status = 4
	WSDeviceStatus_EVICTED     WSDeviceStatus_Status = 5
)

var WSDeviceStatus_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "NEW",
	2: "ONLINE",
	3: "OFFLINE",
	4: "DISAPPEARED",
	5: "EVICTED",
}

var WSDeviceStatus_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"NEW":         1,
	"ONLINE":      2,
	"OFFLINE":     3,
	"DISAPPEARED": 4,
	"EVICTED":     5,
}

func (x WSDeviceStatus_Status) String() string {
	return proto.EnumName(WSDeviceStatus_Status_name, int32(x))
}

func (WSDeviceStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59dc0a049dded467, []int{0, 0}
}

type WSDeviceStatus struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               WSDeviceStatus_Status `protobuf:"varint,2,opt,name=status,proto3,enum=message.WSDeviceStatus_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WSDeviceStatus) Reset()         { *m = WSDeviceStatus{} }
func (m *WSDeviceStatus) String() string { return proto.CompactTextString(m) }
func (*WSDeviceStatus) ProtoMessage()    {}
func (*WSDeviceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_59dc0a049dded467, []int{0}
}

func (m *WSDeviceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSDeviceStatus.Unmarshal(m, b)
}
func (m *WSDeviceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSDeviceStatus.Marshal(b, m, deterministic)
}
func (m *WSDeviceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSDeviceStatus.Merge(m, src)
}
func (m *WSDeviceStatus) XXX_Size() int {
	return xxx_messageInfo_WSDeviceStatus.Size(m)
}
func (m *WSDeviceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_WSDeviceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_WSDeviceStatus proto.InternalMessageInfo

func (m *WSDeviceStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WSDeviceStatus) GetStatus() WSDeviceStatus_Status {
	if m != nil {
		return m.Status
	}
	return WSDeviceStatus_UNKNOWN
}

func init() {
	proto.RegisterEnum("message.WSDeviceStatus_Status", WSDeviceStatus_Status_name, WSDeviceStatus_Status_value)
	proto.RegisterType((*WSDeviceStatus)(nil), "message.WSDeviceStatus")
}

func init() {
	proto.RegisterFile("message/ws.proto", fileDescriptor_59dc0a049dded467)
}

var fileDescriptor_59dc0a049dded467 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x8a,
	0x28, 0xad, 0x67, 0xe4, 0xe2, 0x0b, 0x0f, 0x76, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x0d, 0x2e, 0x49,
	0x2c, 0x29, 0x2d, 0x16, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x62, 0xca, 0x4c, 0x11, 0x32, 0xe3, 0x62, 0x2b, 0x06, 0xcb, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xf0,
	0x19, 0xc9, 0xe9, 0x41, 0x35, 0xeb, 0xa1, 0x6a, 0xd4, 0x83, 0x50, 0x41, 0x50, 0xd5, 0x4a, 0xa1,
	0x5c, 0x6c, 0x50, 0x13, 0xb9, 0xb9, 0xd8, 0x43, 0xfd, 0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0x04, 0x18,
	0x84, 0xd8, 0xb9, 0x98, 0xfd, 0x5c, 0xc3, 0x05, 0x18, 0x85, 0xb8, 0xb8, 0xd8, 0xfc, 0xfd, 0x7c,
	0x3c, 0xfd, 0x5c, 0x05, 0x98, 0x40, 0x2a, 0xfc, 0xdd, 0xdc, 0xc0, 0x1c, 0x66, 0x21, 0x7e, 0x2e,
	0x6e, 0x17, 0xcf, 0x60, 0xc7, 0x80, 0x00, 0x57, 0xc7, 0x20, 0x57, 0x17, 0x01, 0x16, 0x90, 0xac,
	0x6b, 0x98, 0xa7, 0x73, 0x88, 0xab, 0x8b, 0x00, 0x6b, 0x12, 0x1b, 0xd8, 0x07, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x65, 0xf8, 0x27, 0x6c, 0xd5, 0x00, 0x00, 0x00,
}
